### ISSUE TITLE
Servo crash detection looks like it's broken

### ISSUE THREAD

**Issue by jdm** [w3c/wptrunner#105]
https://github.com/servo/servo/pull/5839#issuecomment-96191539

We have no more `expected: CRASH` annotations in the Servo WPT test expectations, and I'm sure we did a few days ago before the wptrunner upgrade.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/7130; please continue all discussion there.
