### ISSUE TITLE
Support changing the viewport size in non-servo executors

### ISSUE THREAD

**Issue by Ms2ger** [w3c/wptrunner#166]

**Comment by gsnedders** [comment]
It's probably worth splitting out the dpi stuff into a separate issue, as that's more obscure, IMO. (i.e., we probably need viewport size support post csswg-test merge as we try and sort out an even bigger case of https://github.com/w3c/web-platform-tests/issues/4619).

**Comment by gsnedders** [comment]
Okay, split that into https://github.com/w3c/wptrunner/issues/240.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/7135; please continue all discussion there.
