### ISSUE TITLE
dismiss_user_prompts uses nonexistent Session.alert property

### ISSUE THREAD

**Issue by jdm** [w3c/wptrunner#203]
After fixing some remaining issues, I got webdriver tests working in Servo, but I hit the code in `dismiss_user_prompts` in `fixtures.py`. It uses `self.client.alert.dismiss()`, where `self.client` is a `wptrunner.executors.webdriver.Session` object. This object has no `alert` property defined, and neither does the `Session` defined in wdclient's client.py (which I have no idea how it's related, but there appears to be a lot of overlap?)

**Comment by jdm** [comment]
I have fixed this in https://github.com/servo/servo/pull/13261/commits/c73ecf7029509542ea78214b7b9c443982702b8a.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/7138; please continue all discussion there.
