### ISSUE TITLE
Add ability to set custom timeout duration for pytest-based tests

### ISSUE THREAD

**Issue by mjzffr** [w3c/wptrunner#229]
There should be a way to set a longer timeout in the wpt manifest for pytest-based tests. 

As far as I can tell, "timeout":"long" only gets added to MANIFEST.json when `<meta name="timeout" content="long">` in html test files.

**Comment by mjzffr** [comment]
Oooh, apparently you can at least set a "long" timeout as in: https://github.com/w3c/wptrunner/issues/229

**Comment by jgraham** [comment]
Well to be clear that actually working depends on https://github.com/w3c/wpt-tools/pull/172 landing. But it will happen.
