### ISSUE TITLE
Error when running https tests in chrome

### ISSUE THREAD

**Issue by mkruisselbrink** [w3c/wptrunner#234]
When trying to use wptrunner to run a https test in chrome, the test passes, but harness status ends up as "ERROR" because `Uncaught SecurityError: Blocked a frame with origin "https://web-platform.test:8443" from accessing a cross-origin frame.`

This error is caused by code in testharnessreport.js, attempting to access the `timeout_multiplier` property of the (cross-origin, since http) `window.opener`.

**Comment by gsnedders** [comment]
Fixed by #215, AIUI.
