### ISSUE TITLE
Make sure screenshots are only taken after fonts have loaded for reftests

### ISSUE THREAD

**Issue by gsnedders** [w3c/wptrunner#241]
see thread from https://lists.w3.org/Archives/Public/public-test-infra/2017JanMar/0024.html

tl;dr: we need to make sure all fonts have loaded before taking screenshots

**Comment by gsnedders** [comment]
https://github.com/w3c/web-platform-tests/pull/5525 shows every browser blocking the load event on fonts? uhhhh. I'm confused now.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/7141; please continue all discussion there.
