### ISSUE TITLE
wptupdate is broken

### ISSUE THREAD

**Issue by Ms2ger** [w3c/wptrunner#46]
```
include_types = set(manifest.item_types) ^ exclude_types
```

at https://github.com/w3c/wptrunner/blob/7825f82f22da3ecabb4102edb3d4548955954863/wptrunner/metadata.py#L269 no longer works, because item_types is gone.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/7126; please continue all discussion there.
