### ISSUE TITLE
Paths marked with `skip: true` in the include_manifest should still be skipped when running with `--include`

### ISSUE THREAD

**Issue by mttr** [w3c/wptrunner#60]

**Comment by jdm** [comment]
@jgraham How difficult would this be? It would be a really big help for minimizing the time it takes to run tests locally while iterating on changes.

**Comment by jdm** [comment]
ie. not spending time trying to figure out why a test doesn't pass that has actually never passed.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/7128; please continue all discussion there.
