### ISSUE TITLE
Make extra positional arguments to wptrunner work like --include

### ISSUE THREAD

**Issue by jgraham** [w3c/wptrunner#66]
So e.g.

    wptrunner dom

should work just like

    wptrunner --include=dom

**Comment by jgraham** [comment]
Better yet wptrunner foo should first check if foo is a url. If it isn't it should check if foo is a file corresponding to some tests and run all the test urls associated with that file.

**Comment by jwatt** [comment]
Can you also allow positional arguments and --tests to point to a single test?

**Comment by jwatt** [comment]
Note also |mach mochitest-plain|'s

  --start-at START_AT   Start running the test sequence at this test.
  --end-at END_AT       Stop running the test sequence at this test.

which are occasionally useful for running a sub-range.

**Comment by jgraham** [comment]
Well we don't have --start-at and --end-at but the rest of this got fixed some time ago.
